name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Say hello
        run: echo "Hello World!"

      - name: Print the date
        run: date

      - name: List current directory
        run: ls -l